name: teste

on: push

jobs:
  pipeline:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository      
        uses: actions/checkout@v2
      
      - name: Convair
        uses: actions/teste@v1
        with:
          repository: trintoni/actions