name: teste

on: push

jobs:
  pipeline:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository      
        uses: actions/checkout@v2
      
      - name: Convair
        uses: actions/checkout@v2
        with:
          repository: trintoni/actions
          path: ./.actions

      - name: Define Branch Type
        uses: ./.actions/teste