name: teste

on: push

jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: "echo Hello World Bitch"

  test_python:
    uses: trintoni/actions/teste/teste@v1.0